### ISSUE TITLE
Hook alumni profiles up to the members

### ISSUE THREAD

**Issue by disa-mhembere** [aschiffhauer/upe#2]
I'm not sure how we want to integrate alums. I made their bios but they are not linked into the site yet.

They're in `bios/alumni`.

**Comment by schiffy91** [comment]
I'm currently working on this

**Comment by disa-mhembere** [comment]
Awesome!

Disa Mhembere
Johns Hopkins University
:(){:|:&};:

**Comment by disa-mhembere** [comment]
I have to reopen this because the alums who submitted bios will expect to see them there when this launches. The format doesn't matter to me at all, but they must be there in some shape or form. Open to suggestions as to how they will be integrated

**Comment by schiffy91** [comment]
I spent about 8 hours on this yesterday, so I'm tapping out for the next few weeks.  If you think this is hi pri, feel free to implement and close; otherwise, I'll get to it before the site launches.  

It's very simple to add profiles. For our alumni, specifically (since they already exist in `members.json`):
- Find their entry in `members.json`
- Look at a member with a profile in `members.json` (e.g. you or me)
- Fill in the appropriate fields (or leave blank if they don't exist.  If no image exists, link to the image placeholder for now.)
- `python members.py`
- Commit changes

Sorry that there's not better documentation, will add use cases before launch.

Let me know if you have any problems

**Comment by disa-mhembere** [comment]
Sure. This will not be a problem for me to do at some point this week. Just wanted to make sure they existed. Great work btw. Looks good. 

Disa Mhembere
Johns Hopkins University
:(){:|:&};:

**Comment by schiffy91** [comment]
Disa, I believe you finished this up, correct? If not, please re-open it!

**Comment by disa-mhembere** [comment]
Yeah I should have closed it

Disa Mhembere
Johns Hopkins University
:(){:|:&};:
